### ISSUE TITLE
Adding multiple endpoints

### ISSUE THREAD

**Issue by dchallener** [mattbrailsford/umbraco-headrest#6]
This is an absolutely fantastic project!  So simple to get started.  I have a question regarding multiple endpoints that I can't seem to get to work and wanted some clarification.

Is the idea that we set up multiple configure endpoint calls to register API roots? eg I would like a call at "/" for Homepage, but also an endpoint "/locations/" to retrieve a list of locations?  If I already have content at /locations in the back office, will this auto route if the same doctype as homepage or is an explicit configuration required for each endpoint to be exposed?

**Comment by mattbrailsford** [comment]
The API route is kinda like "the virtual path you want your API to hang off". You can then provide an XPath to say which node should be concidered the root node (defaults to the Umbraco root node) for that endpoint, and then all nodes after that use their Umbraco URL alias to create subsequent URLs sprouting off the route API url.

So say you have the site structure:

- Home
  - Locations
    - Location 1
    - Location 2

And a config with a root path of `/api/` and the XPath being the default and thus point to the root node, then the endpoint will expose the following urls:

- `/api/` - Home node content
- `/api/locations/` - Locations node content
- `/api/locations/location-1/` - Location 1 node content
- `/api/locations/location-2/` - Location 2 node content

As you can see then, HeadRest uses the route path as kinda of a prefix for node urls with each node below the XPath root dynamically building up the API.

Ultimaltey then, most people will just expose 1 API endpoint from which all the umbraco nodes will dynamically build the inner API routes. So you don't need to define an endpoint for each URL you want to expose, you just say where in the node tree you want to start, and from what sub URL (if any, so if you use the default '/' this will essentially feed the content via the regular Umbraco URLs) you want your API to be exposed.

Hope that helps clarify.

Matt

**Comment by dchallener** [comment]
That is perfect. I can see exactly what I've done wrong - I had put locations as a sibling to home node so therefore creating multiple root nodes which it didn't like at all.  

The one configuration is perfect and how I expected it to work from your documentation.

Just to box off my understanding of this, when I hit `/api/locations/` I would like to return the child locations at this point.  Can you specify a controller to be called here or do you extend the api HeadRestController and say if this doctype then map these nodes to a field called Children?  Or is there a fairly straightforward automapper resolver way of doing this I'm missing!

Thank you for your time,
David

**Comment by mattbrailsford** [comment]
@dchallener HeadRest purely takes the request and maps the current ModelsBuilder model for that page to the defined view model in your config via (by default) AutoMapper. What your mapping logic does and what your view model looks like is completely up to you, so if on your locations route, you want to show a list of locations, you can create a view model that has an `IEnumerable<LocationViewModel>` and then define an Auto Mapping config to map the Locations Children property to that collection. ie :
````csharp
// LocationsPage view model
public class LocationsPageViewModel {
    public IEnumerable<LocationPageViewModel> Locations { get; set; }
}

// Individual LocationPage view model
public class LocationPageViewModel {
    ....
}
````
````csharp
// LocationsPage mapping
Mapper.CreateMap<LocationsPage, LocationsPageViewModel>()
    .ForMember(x => x.Locations, o => o.MapFrom(y => y.Children));

// Individual LocationPage mapping
Mapper.CreateMap<LocationPage, LocationPageViewModel>();
````

**Comment by dchallener** [comment]
Thank you - this is exactly what I've got (I needed the locationPage mapping for it to work).  You're a star.

Out of curiosity, and probably my lack of familiarity of automapper, if you wanted to do a bit of logic using the ModelsBuilder model, methods that traditionally live in a controller - ie querystring parameter handling, or paging etc.  Is there a configuration option to do this?

For example, if you wanted to filter another list, say Projects, by a specific location (where locations are multi content picked)

- Home
  - Locations
    - Location 1
    - Location 2
  - Projects
    - Project 1
    - Project 2

the call would be to `/api/projects/?location=1` would it be possible to retrieve this parameter (looks like CustomRouteMappings might do this) but this parameter I'd like to affect which projects are returned in my viewModel?

**Comment by mattbrailsford** [comment]
Hi @dchallener. For that, the best approach I've found so far is to use an AutoMapper `IValueResolver` which is a class that lets you define some custom logic to resolve a value. You then tell your AutoMapper mapping to use the custom resolver for a given property.

````csharp
public class MyCustomResolver : IValueResolver 
{
    public ResolutionResult Resolve(ResolutionResult source)
    {
        var page = source.Context.SourceValue as MyPageType;
        // Do some custom logic here
        return source.New(result);
    }
}
````

````csharp
Mapper.CreateMap<LocationsPage, LocationsPageViewModel>()
    .ForMember(x => x.Locations, o => o.ResolveUsing<MyCustomResolver>());
````
In the custom resolver, you could then probably access the current `HttpContext` in order to access any querystring parameters and to do some logic based on the result.

-----------

If you want a more advanced solution, you could look in my repository here https://github.com/mattbrailsford/nullorwhitespace-backend in which I have an example config setup for a route `/blog/` which handles pagination urls like `/blog/2/`, `/blog/3/` etc.

Essentially in my endpoint config, I define a custom route mapping using a regex to extract the number into a variable (see https://github.com/mattbrailsford/nullorwhitespace-backend/blob/master/NullOrWhitespace/Bootstrap.cs#L36) and then have a custom `IValueResolver` to get the paginated list of blog posts (see https://github.com/mattbrailsford/nullorwhitespace-backend/blob/master/NullOrWhitespace/Web/Mapping/Resolvers/PagniatedBlogPostsResolver.cs). In there, because I'm using a custom HeadRest route mapping, I can use a custom context HeadRest passes to AutoMapper to retrive any parsed route params:

````csharp
var context = source.Context.GetHeadRestMappingContext();
if (context == null)
    return source.Ignore();

var page = context.Request.HeadRestRouteParam("page", 1);
````

I then use that param to do my logic and return the paginated list of results, and then this is all hooked up to AutoMapper in my mapping config (see https://github.com/mattbrailsford/nullorwhitespace-backend/blob/master/NullOrWhitespace/Web/Mapping/ViewModelMappingProfile.cs#L42)

**Comment by mattbrailsford** [comment]
I've put a seperator in the reply above as the later half gets quite specific and I'm expecting you to go do some reading up on the Links I've posted, but ultimately the simple answer to your question is above the seperator. Just want to make that clearer.

**Comment by dchallener** [comment]
This is great, I genuinely didn't think you could put Examine queries in a resolver but it makes perfect sense and I can definitely work out the approach from your detailed explanation.

**Comment by mattbrailsford** [comment]
Awesome. Glad I could help.
