### ISSUE TITLE
Caching of API requests

### ISSUE THREAD

**Issue by dchallener** [mattbrailsford/umbraco-headrest#7]
Hi Matt,

I was wondering whether you use any caching techniques when utilising the API?  Or if there were any plans to add a basic cached response on the HeadRestController at all?

I'm finding the majority of the time it is very performant but every now and then the API goes a bit sluggish, probably due to inactivity for a while. Have you experienced this at all?

Many thanks,
David

**Comment by mattbrailsford** [comment]
@dchallener sorry for the late reply. I haven't done anything myself, but because HeadRest feeds JSON responses through a standard Controller and not an ApiController, you could probably use standard output caching.

In theory, you should be able to create your own controller, inheriting from `HeadRestController` and then override the Index action, adding the output cache directive. 

    public class MyHeadRestController : HeadRestController {

        [OutputCache(...)]
        public override ActionResult Index(RenderModel model) {
            return base.Index(model);
        }

    }

Then you can tell HeadRest to use your controller in the config.

    ...
    ControllerType = typeof(MyHeadRestController),
    ...

**Comment by dchallener** [comment]
@mattbrailsford I didn't see this come in. Thanks for responding - I did pretty much exactly this in the end and it worked great.

Many thanks,
David
